- defaults:
    link:
      relink: true

- clean: ['~']

- create:
    ~/.config:
      mode: 0755

- link:
    ~/.config/:
      glob: true
      path: config/*
      exclude:
        - config/gitconfig
        - config/lftp
        - config/tmux
        - config/vim
        - config/zsh
        - config/iterm2
    
    # Non XDG configs
    ~/.gitconfig: config/git/gitconfig
    ~/.lftprc: config/lftp/lftprc
    ~/.tmux.conf: config/tmux/tmux.conf
    ~/.vimrc: config/vim/vimrc
    ~/.zprofile: config/zsh/zprofile
    ~/.zshrc: config/zsh/zshrc
    ~/Library/Application Support/tlrc/config.toml: config/tldr/config.toml

- shell:
    - ['git submodule update --init --recursive', Initialize Git submodules]
