# ----------------------------------------
# Aider config
# ----------------------------------------

# Only OpenAI and Anthropic API keys can be included in the YAML config
# Keys for all APIs can be stored in a .env file: https://aider.chat/docs/config/dotenv.html

# ----------------------------------------
# Options
# ----------------------------------------

# help: xxx # Show this help message and exit

# ----------------------------------------
# Main Model
# ----------------------------------------

model: gemini-2.5-pro-preview-05-06

# ----------------------------------------
# Output Settings
# ----------------------------------------

pretty: true # colorized output
# dark-mode: true
# light-mode: true
# stream: true

# Custom colors (hex values)
user-input-color: "#9ece6a"
#tool-output-color: "xxx"
tool-error-color: "#f7768e"
tool-warning-color: "#d8b072"
assistant-output-color: "#90ccfa"

# Completion menu colors
completion-menu-color: "#9ece6a"
completion-menu-bg-color: "#000000"
completion-menu-current-color: "#00ffff"
completion-menu-current-bg-color: "#9ece6a"

# code-theme: default # see pygments builtin style (https://pygments.org/styles)

show-diffs: true

# ----------------------------------------
# Other Settings
# ----------------------------------------

# Specify which editor to use for the /editor command
editor: nvim
