# ----------------------------------------
# Aider config
# ----------------------------------------

# Note: You can only put OpenAI and Anthropic API keys in the YAML
# config file. Keys for all APIs can be stored in a .env file:
# https://aider.chat/docs/config/dotenv.html

# ----------------------------------------
# Options
# ----------------------------------------

# Show this help message and exit
# help: xxx

# ----------------------------------------
# Main Model
# ----------------------------------------

# Specify the model to use for the main chat
model: gemini-2.5-pro

# ----------------------------------------
# Output Settings
# ----------------------------------------

# Use colors suitable for a dark terminal background
# dark-mode: true

# Use colors suitable for a light terminal background
# light-mode: false

# Enable/disable pretty, colorized output (default: True)
pretty: true

# Enable/disable streaming responses (default: True)
# stream: true

# Set custom colors (hex values)
user-input-color: "#9ece6a"
tool-output-color: "xxx"
tool-error-color: "#FF2222"
tool-warning-color: "#FFA500"
assistant-output-color: "#0088ff"

# Completion menu colors
# completion-menu-color: "xxx"
# completion-menu-bg-color: "xxx"
# completion-menu-current-color: "xxx"
# completion-menu-current-bg-color: "xxx"

# Markdown code theme (default: default)
# Other options: monokai, solarized-dark, solarized-light,
# or a Pygments builtin style (https://pygments.org/styles)
# code-theme: default

# Show diffs when committing changes
# show-diffs: false

# ----------------------------------------
# Other Settings
# ----------------------------------------

# Use VI editing mode in the terminal
vim: true

# Specify which editor to use for the /editor command
editor: nvim
