# ----------------------------------------
# Aider config
# ----------------------------------------

# See also: https://aider.chat/docs/config/dotenv.html

# ----------------------------------------
# Options
# ----------------------------------------

# help: xxx # Show this help message and exit

# ----------------------------------------
# Main Model
# ----------------------------------------

model: gemini-2.5-pro-preview-05-06

# ----------------------------------------
# Output Settings
# ----------------------------------------

pretty: true # colorized output
# dark-mode: true
# light-mode: true
# stream: true

# Custom colors (hex values)
user-input-color: "#9ece6a"
#tool-output-color: "xxx"
tool-error-color: "#f7768e"
tool-warning-color: "#d8b072"
assistant-output-color: "#c1c9f1"

# Completion menu colors
completion-menu-color: "#9ece6a"
completion-menu-bg-color: "#000000"
completion-menu-current-color: "#000000"
completion-menu-current-bg-color: "#9ece6a"

code-theme: friendly-grayscale # https://pygments.org/styles

show-diffs: true

# ----------------------------------------
# Other Settings
# ----------------------------------------

# Specify which editor to use for the /editor command
editor: nvim
