# ----------------------------------------
# SSH Agent
# ----------------------------------------

if [[ -z "$SSH_AUTH_SOCK" ]]; then
    eval "$(ssh-agent -s)" > /dev/null
fi

# ----------------------------------------
# Homebrew
# ----------------------------------------

if [[ "$(arch)" == "arm64" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"

    BREW_PREFIX="/opt/homebrew"
    INTEL_BREW_PREFIX="/usr/local"

    if [[ -x "$INTEL_BREW_PREFIX/bin/brew" ]]; then
        PATH="$PATH:$INTEL_BREW_PREFIX/bin:$INTEL_BREW_PREFIX/sbin"
    fi
else
    eval "$(/usr/local/bin/brew shellenv)"
    BREW_PREFIX="/usr/local"
fi

# ----------------------------------------
# Locale & Editor
# ----------------------------------------

export LANG=en_US.UTF-8
export EDITOR="nvim"

# ----------------------------------------
# Paths
# ----------------------------------------

 for pkg in coreutils findutils gnu-sed grep gawk; do
     gnu_bin="$BREW_PREFIX/opt/$pkg/libexec/gnubin"
     [[ -d "$gnu_bin" ]] && PATH="$gnu_bin:$PATH"
 done

 PATH="$HOME/.local/bin:$PATH"
 PATH="$BREW_PREFIX/bin:$BREW_PREFIX/sbin:$PATH"

 [[ $(arch) != "arm64" ]] && PATH="/usr/local/bin:/usr/local/sbin:$PATH"
 PATH="/opt/local/bin:/opt/local/sbin:$PATH"
 PATH="$PATH:/Library/TeX/texbin"

 export PATH

# DYLD Library
# export DYLD_LIBRARY_PATH="$BREW_PREFIX/lib:$DYLD_LIBRARY_PATH"
# export DYLD_FALLBACK_LIBRARY_PATH="$BREW_PREFIX/lib:/usr/lib"

# ----------------------------------------
# SDKMAN Initialization
# ----------------------------------------

export SDKMAN_DIR=$(brew --prefix sdkman-cli)/libexec
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

export JAVA_HOME="/opt/homebrew/opt/sdkman-cli/libexec/candidates/java/current/"

# ----------------------------------------
# Python
# ----------------------------------------

export VIRTUAL_ENV_DISABLE_PROMPT=1 # disable venv prompt in lieu of custom one

# ----------------------------------------
# Misc.
# ----------------------------------------

export PROFILE_SOURCED=1
