[[ssh-keys]]
item = "id_ed25519_github"

[[ssh-keys]]
item = "id_ed25519_github_personal"

[[ssh-keys]]
item = "id_ed25519_github_ubc"

[[ssh-keys]]
item = "id_ed25519_opnsense"

[[ssh-keys]]
item = "id_ed25519_proxmox"

[[ssh-keys]]
item = "id_ed25519_glance"

[[ssh-keys]]
item = "id_ed25519_speedtest-tracker"

[[ssh-keys]]
item = "id_ed25519_caddy"

[[ssh-keys]]
item = "id_ed25519_ubc_remote"
