# ----------------------------------------
# Locale
# ----------------------------------------

export LANG=en_US.UTF-8

# ----------------------------------------
# Default Editor
# ----------------------------------------

export EDITOR='nvim'

# ----------------------------------------
# Paths
# ----------------------------------------

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin:/Users/cyanghxst/.cargo/bin:/Users/cyanghxst/.local/share/bob/nvim-bin:$PATH"
export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
export PATH="$PATH:/Library/TeX/texbin"
export DYLD_LIBRARY_PATH="/opt/homebrew/lib:$DYLD_LIBRARY_PATH"
export DYLD_FALLBACK_LIBRARY_PATH="/opt/homebrew/lib:/usr/lib"

# ----------------------------------------
# pyenv Environment
# ----------------------------------------

export PYENV_ROOT="$HOME/.pyenv"
if [[ -d $PYENV_ROOT/bin ]]; then
    export PATH="$PYENV_ROOT/bin:$PATH"
fi
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init --path)"
fi


# ----------------------------------------
# rbenv
# ----------------------------------------

eval "$(rbenv init -)"

# ----------------------------------------
# SDKMAN Initialization
# ----------------------------------------

export SDKMAN_DIR=$(brew --prefix sdkman-cli)/libexec
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"

# ----------------------------------------
# Brew Environment
# ----------------------------------------

if [ "$(arch)" = "arm64" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    eval "$(/usr/local/bin/brew shellenv)"
fi
