# ----------------------------------------
# Locale
# ----------------------------------------

export LANG=en_US.UTF-8

# ----------------------------------------
# Default Editor
# ----------------------------------------

export EDITOR='nvim'

# ----------------------------------------
# Paths
# ----------------------------------------

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:$PATH"
export PATH="$PATH:/Library/TeX/texbin"

# DYLD Library
export DYLD_LIBRARY_PATH="/opt/homebrew/lib:$DYLD_LIBRARY_PATH"
export DYLD_FALLBACK_LIBRARY_PATH="/opt/homebrew/lib:/usr/lib"

# ----------------------------------------
# Brew Environment
# ----------------------------------------

if [ "$(arch)" = "arm64" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    eval "$(/usr/local/bin/brew shellenv)"
fi
