[tools]
gradle = "latest"
# java = "temurin-21.0.6+7.0.LTS"
maven = "latest"
node = "latest"
python = "latest"
rust = "latest"
usage = "latest"
zig = "latest"

[settings]

[settings.github]
credential_command = "op item get github-cli-1password --fields token --reveal"
